export const LIST_TRIP_REQUEST = 'LIST_TRIP_REQUEST'
export const LIST_TRIP_SUCCESS = 'LIST_TRIP_SUCCESS'
export const LIST_TRIP_FAIL = 'LIST_TRIP_FAIL'


export const  DETAIL_TRIP_REQUEST = "DETAIL_TRIP_REQUEST"
export const  DETAIL_TRIP_SUCCESS = "DETAIL_TRIP_SUCCESS"
export const  DETAIL_TRIP_FAIL = "DETAIL_TRIP_FAIL"