export const USER_SIGN_IN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGN_IN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGN_IN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGN_OUT = "USER_SIGNIN_OUT"

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST"
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL"

export const USER_MESSAGE = 'USER_MESSAGE'