const data = [
    {
        _id: 1,
        name: "Discover the city's party scene",
        perPerson: 35,
        total: 167,
        numReviews: 65,
        rating: 5,
        place: "NightLife - New York",
        category: "experiences",
        thumbnail: "/images/city's_party.png",
        frontView: "/images/out1.jpg",
        innerView: "/images/int1.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide1.jpg",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free You’ll love my place for its lovely and bright looks comfortable stayBangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay.Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm"
    },
    {
        _id: 2,
        name: "Tour with an Enthusiastic Local",
        perPerson: 3,
        total: 77,
        numReviews: 1,
        rating: 5,
        place: "Entertainment - Vancouver",
        category: "experiences",
        thumbnail: "/images/tour_and_entusistic.png",
        frontView: "/images/out2.jpg",
        innerView: "/images/int2.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 2,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        cleaner: 5,
        superHost: "Edwards",
        guideThumbnail: "/images/guide2.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius dignissimos iure neque dolore natus hic repellendus sit nulla cum illo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore cum minima a aspernatur eos asperiores earum aliquam distinctio iste maiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Id quidem ea consequatur magnam deserunt, ducimus tempore, nemo omnis, dignissimos praesentium porro beatae debitis labore numquam aliquam voluptates doloremque tempora eius?"
    },
    {
        _id: 3,
        name: "Retro Photos",
        perPerson: 49,
        total: 137,
        numReviews: 72,
        rating: 5,
        place: "Photography - Texas",
        category: "experiences",
        thumbnail: "/images/retro.png",
        frontView: "/images/out3.jpg",
        innerView: "/images/int3.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 1,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide3.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae, illum praesentium veniam qui odio, dolore quasi minima vero tempore neque at animi delectus id eos pariatur nostrum dolorem consequatur deserunt officia nesciunt ex voluptates asperiores, officiis dolores. Aliquam consequuntur, dolore facere animi provident similique ullam?"
    },
    {
        _id: 4,
        name: "Must Have L.A Pictures!",
        perPerson: 35,
        total: 51,
        numReviews: 132,
        rating: 5,
        place: "PhotoClass - New York",
        category: "experiences",
        thumbnail: "/images/must.png",
        frontView: "/images/out4.jpg",
        innerView: "/images/int4.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide.png",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free You’ll love my place for its lovely and bright looks comfortable stayBangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay.Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm"
    },
    {
        _id: 5,
        name: "Unique Cob Cottage",
        perPerson: 128,
        total: 284,
        numReviews: 308,
        rating: 5,
        place: "NightLife - New York",
        category: "homes",
        thumbnail: "/images/cottage.png",
        frontView: "/images/out5.jpg",
        innerView: "/images/int5.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide.png",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free You’ll love my place for its lovely and bright looks comfortable stayBangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay.Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm"
    },
    {
        _id: 6,
        name: "The Joshua Tree House",
        perPerson: 250,
        total: 381,
        numReviews: 507,
        rating: 4.5,
        place: "NightLife - New York",
        category: "homes",
        thumbnail: "/images/tree-house.png",
        frontView: "/images/out6.jpg",
        innerView: "/images/int6.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide2.jpg",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free You’ll love my place for its lovely and bright looks comfortable stayBangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay.Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm"
    },
    {
        _id: 7,
        name: "A Pirate's Life For Me - Houseboat!",
        perPerson: 35,
        total: 259,
        numReviews: 0,
        rating: 0,
        place: "NightLife - New York",
        category: "homes",
        thumbnail: "/images/pirate.png",
        frontView: "/images/out7.jpg",
        innerView: "/images/int7.jpg",
        location: "Dhaka, Bangladesh",
        guestCapacity: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        cleaner: 10,
        superHost: "Rowdra",
        guideThumbnail: "/images/guide.png",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias doloremque laboriosam saepe doloribus et cupiditate omnis eligendi ratione error perferendis, iure numquam amet dicta optio modi harum assumenda ab sit maxime ut aperiam dolore earum voluptatem fugit! Culpa commodi, nesciunt voluptates natus quidem vitae omnis maxime incidunt eum illum distinctio tenetur ab? Velit, saepe. Debitis, dolor atque alias sapiente quis ea modi corporis. Quo atque porro sit provident dolore quam at laborum ex ipsam repellat earum repudiandae libero eos commodi cum fuga nesciunt veniam, est facere. At labore fugiat, quas, itaque atque, ipsa nostrum ab sequi tempore aliquam tempora mollitia."
    },
]

export default data